version: "3.7"
services:
  image:
    build: .
    image: homecentr/dhcp:preview
    volumes:
      - ./example:/config
    cap_add:
      - "NET_RAW" # Required for LPF  
      - "CAP_NET_BIND_SERVICE" # Required to bind on port < 1024
    cap_drop:
      - "ALL"
    networks:
      default:
    tmpfs:
    - /leases:mode=770,uid=1000,gid=1000

  client:
    build: ./tests
    networks:
      default:

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "172.19.250.0/24"